project:
  type: book
  output-dir: docs

book:
  title: BAN430 Forecasting 
  author: "Sondre Hølleland"
  date: "9.8.2022"
  page-footer: 
    center: "Copyright 2022, Sondre Hølleland" 
  logo: "bilder/nhh.png"
  alignment: "left"
  chapters:
    - index.qmd
    - 1_randrstudio.qmd
    - 2_timeseriesgraphics.qmd
    - 3_decomposition.qmd
    - 4_timeseriesfeatures.qmd
    - 5_forecasterstoolbox.qmd
    - 6_judgementalforecast.qmd
    - 7_regressionmodels.qmd
    - 8_ARIMAmodels.qmd
    - 9_Volatitiliy_forecasting.qmd
    - 10_Practicle_forecasting_issues.qmd
    - references.qmd


bibliography: references.bib

sidebar:
  style: "docked"
  alignment: "left"
  border: true
  number-depth: 3




format:
  html:
    toc: true
    alignment: left
    toc-depth: 4
    toc-title: Chapter contents
    toc-location: left
    page-layout: full
    theme: 
    - cosmo
    - custom.scss
    css: style.css
    fontsize: 1.1em
    linestretch: 1.7
    html-math-method: katex
  pdf:
    documentclass: scrreprt

editor: visual
server: shiny


body-footer: | 
  Sondre Hølleland


