project:
  type: book
  output-dir: docs

book:
  title: BAN430 Forecasting
  author: "Sondre Hølleland"
  date: "9.8.2022"
  alignment: "left"
  chapters:
    - index.qmd
    - randrstudio.qmd
    - 2_timeseriesgraphics.qmd
    - 3_decomposition.qmd
    - references.qmd


bibliography: references.bib

sidebar:
  style: "docked"
  alignment: "left"
  border: true
  logo: "bilder/nhh.png"
  number-depth: 3


format:
  html:
    toc: true
    toc-depth: 4
    toc-title: Chapter contents
    toc-location: left
    theme: 
    - cosmo
    - custom.scss
    css: style.css
    fontsize: 1.1em
    linestretch: 1.7
    html-math-method: katex
  pdf:
    documentclass: scrreprt

editor: visual


body-footer: | 
  Sondre Hølleland
margin-header: |
   <a href="https://www.nhh.no/"><img src="bilder/nhh.png" width="240"></a>

