project:
  type: website
  output-dir: docs

website:
  title: "BAN430 Forecasting"
  image: bilder/nhh.png
  page-navigation: true
  navbar:
    logo: bilder/nhh.png
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    title: "Whatever"
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Course overview
      - section: "1 R and Rstudio"
        contents:
          - href: 1_installingrandrstudio.qmd
            text: "Installing R and Rstudio"
          - href: 1_rrecap.qmd
            text: "Recap R"
      - section: "2 Time series basics"
        contents:
          - 2_timeseriesgraphics.qmd
      - section: "3 Adjustments and decomposition"
        href: 3_decomposition_intro.qmd 
        contents:
          - 3_adjustments.qmd
          - 3_timeseriesdecomposition.qmd
          - 3_exercises.qmd
      - section: "4 Time series features"
        contents:
          - 4_timeseriesfeatures.qmd
          - 4_features.qmd
          - 4_tourismexample.qmd
          - 4_exercises.qmd
      - section: "5 Forecasters toolbox"
        contents:
          - 5_forecasterstoolbox.qmd
      - section: "6 Judgemental forecast"
        contents:
          - 6_judgementalforecast.qmd
      - section: "7 Regression models"
        contents:
          - 7_regressionmodels.qmd
      - section: "8 ARIMA models"
        contents:
          - 8_ARIMAmodels.qmd
      - section: "9 Volatility forecasting"
        href: 9_Volatitiliy_forecasting.qmd
        contents:
          - 9_arch.qmd
          - 9_garch.qmd
          - 9_forecast_garch.qmd
          - 9_forecasting_garch_R.qmd
      - section: "10 Practical forecasting issues"
        contents:
          - 10_Practicle_forecasting_issues.qmd
      - section: "Workshops"
        contents: 
          - W0_tsibble.qmd
          - W1_traffic.qmd
          - W2_electricityprices.qmd
      - section: "Appendix"
        contents:
          - 12_data_appendix.qmd
      - href: references.qmd
        text: "References"

editor: visual


          
format:
  html:
    theme: 
        - cosmo
        - custom.scss
    css: style.css
    fontsize: 1.1em
    linestretch: 1.7
    html-math-method: katex
